name: env_semantic_image_segmentation_py36
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - apptools=4.4.0=py36_1
  - argon2-cffi=20.1.0=py36h8c4c3a4_1
  - async_generator=1.10=py_0
  - attrs=20.1.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - blas=1.0=mkl
  - bleach=3.1.5=pyh9f0ad1d_0
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2020.6.20=hecda079_0
  - certifi=2020.6.20=py36h9880bd3_2
  - cffi=1.11.5=py36_0
  - cloudpickle=1.4.1=py_0
  - configobj=5.0.6=py36_1
  - cudatoolkit=10.2.89=hfd86e86_1
  - curl=7.69.1=hbc83047_0
  - cycler=0.10.0=py36_0
  - cytoolz=0.10.1=py36h7b6447c_0
  - dask-core=2.16.0=py_0
  - dbus=1.13.12=h746ee38_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - embree=2.14.0=0
  - entrypoints=0.3=py36h9f0ad1d_1001
  - envisage=4.8.0=py_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - future=0.18.2=py36_0
  - geos=3.8.1=he1b5a44_0
  - glib=2.56.2=hd408876_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.10.0=py36h7918eee_0
  - hdf4=4.2.13=h3ca952b_2
  - hdf5=1.10.4=hb1b8bf9_0
  - icu=58.2=he6710b0_3
  - imagecodecs-lite=2019.12.3=py36h785e9b2_1
  - imageio=2.8.0=py_0
  - importlib-metadata=1.7.0=py36h9f0ad1d_0
  - importlib_metadata=1.7.0=0
  - intel-openmp=2020.1=217
  - ipykernel=5.3.4=py36h95af2a2_0
  - ipython=5.8.0=py36_1
  - ipython_genutils=0.2.0=py_1
  - jinja2=2.11.2=pyh9f0ad1d_0
  - joblib=0.16.0=py_0
  - jpeg=9b=habf39ab_1
  - jsoncpp=1.8.4=hfd86e86_0
  - jsonschema=3.2.0=py36h9f0ad1d_1
  - jupyter_client=6.1.7=py_0
  - jupyter_core=4.6.3=py36h9f0ad1d_1
  - jupyterlab_pygments=0.1.1=pyh9f0ad1d_0
  - kiwisolver=1.2.0=py36hfd86e86_0
  - krb5=1.17.1=h173b8e3_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.8.0=16_mkl
  - libcblas=3.8.0=16_mkl
  - libcurl=7.69.1=h20c2e04_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.3=he6710b0_1
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - liblapack=3.8.0=16_mkl
  - libnetcdf=4.6.1=h11d0813_2
  - libogg=1.3.2=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.18=h516909a_0
  - libspatialindex=1.9.3=he1b5a44_3
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtheora=1.1.1=h5ab3b9f_1
  - libtiff=4.1.0=h2733197_0
  - libuuid=1.0.3=h1bed415_2
  - libvorbis=1.3.6=h7b6447c_0
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - lz4-c=1.8.1.2=h14c3975_0
  - markupsafe=1.1.1=py36h8c4c3a4_1
  - matplotlib=3.1.3=py36_0
  - matplotlib-base=3.1.3=py36hef1b27d_0
  - mayavi=4.7.1=py36h94891b3_2
  - mistune=0.8.4=py36h8c4c3a4_1001
  - mkl=2020.1=217
  - mkl-service=2.3.0=py36he904b0f_0
  - mkl_fft=1.0.15=py36ha843d7b_0
  - mkl_random=1.1.0=py36hd6b4f25_0
  - nbclient=0.5.0=py_0
  - nbconvert=6.0.2=py36h9f0ad1d_0
  - nbformat=5.0.7=py_0
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.4.0=py_0
  - networkx=2.4=py_0
  - ninja=1.10.0=hc9558a2_0
  - notebook=6.1.3=py36h9f0ad1d_0
  - numpy=1.18.1=py36h4f9e942_0
  - numpy-base=1.18.1=py36hde5b4d6_1
  - olefile=0.46=py_0
  - openssl=1.1.1h=h516909a_0
  - packaging=20.4=pyh9f0ad1d_0
  - pandas=1.0.3=py36h0573a6f_0
  - pandoc=2.10.1=h516909a_0
  - pandocfilters=1.4.2=py_1
  - pcre=8.43=he6710b0_0
  - pexpect=4.8.0=py36h9f0ad1d_1
  - pickleshare=0.7.5=py36h9f0ad1d_1001
  - pillow=7.1.2=py36hb39fc2d_0
  - pip=20.0.2=py36_3
  - plotly=4.7.1=py_0
  - prometheus_client=0.8.0=pyh9f0ad1d_0
  - prompt_toolkit=1.0.15=py_1
  - ptyprocess=0.6.0=py_1001
  - pycparser=2.20=pyh9f0ad1d_2
  - pyembree=0.1.6=py36h830a2c2_1
  - pyface=6.1.2=py36_0
  - pygments=2.6.1=py_0
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py36h22d08a2_1
  - pyrsistent=0.16.0=py36h8c4c3a4_0
  - python=3.6.10=h7579374_2
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - pytorch=1.5.1=py3.6_cuda10.2.89_cudnn7.6.5_0
  - pytz=2020.1=py_0
  - pywavelets=1.1.1=py36h7b6447c_0
  - pyzmq=19.0.2=py36h9947dbf_0
  - qt=5.9.7=h5867ecd_1
  - readline=8.0=h7b6447c_0
  - retrying=1.3.3=py36_2
  - rtree=0.9.4=py36he053a7a_1
  - scikit-image=0.17.2=py36h830a2c2_1
  - scikit-learn=0.23.1=py36h0e1014b_0
  - scipy=1.5.2=py36h3a855aa_0
  - send2trash=1.5.0=py_0
  - setuptools=46.2.0=py36_0
  - shapely=1.7.0=py36h3d6ee9d_3
  - simplegeneric=0.8.1=py_1
  - sip=4.19.13=py36he6710b0_0
  - six=1.14.0=py36_0
  - sqlite=3.31.1=h62c20be_1
  - tbb=2020.0=hfd86e86_0
  - terminado=0.8.3=py36h9f0ad1d_1
  - testpath=0.4.4=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tifffile=2020.6.3=py_0
  - tk=8.6.8=hbc83047_0
  - toolz=0.10.0=py_0
  - torchvision=0.6.1=py36_cu102
  - tornado=6.0.4=py36h7b6447c_1
  - tqdm=4.46.0=py_0
  - traitlets=4.3.3=py36h9f0ad1d_1
  - traits=6.0.0=py36h14c3975_0
  - traitsui=6.1.3=py_0
  - trimesh=3.7.0=pyh9f0ad1d_0
  - vispy=0.5.3=py36hee6b756_0
  - vtk=8.2.0=py36haa4764d_200
  - wcwidth=0.2.5=pyh9f0ad1d_1
  - webencodings=0.5.1=py_1
  - wheel=0.34.2=py36_0
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.2=he1b5a44_3
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - absl-py==0.9.0
    - albumentations==0.4.6
    - cachetools==4.1.1
    - chardet==3.0.4
    - freetype-py==2.2.0
    - google-auth==1.19.2
    - google-auth-oauthlib==0.4.1
    - grpcio==1.30.0
    - idna==2.10
    - imagesize==1.2.0
    - imgaug==0.4.0
    - markdown==3.2.2
    - mesh-to-sdf==0.0.12
    - nbtex==1.0.1
    - numexpr==2.7.1
    - oauthlib==3.1.0
    - opencv-python-headless==4.3.0.36
    - protobuf==3.12.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyglet==1.5.8
    - pyoctree==0.2.10
    - pyopengl==3.1.0
    - pyrender==0.1.43
    - pywavefront==1.3.2
    - pyyaml==5.3.1
    - requests==2.24.0
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - tables==3.6.1
    - tensorboard==2.2.2
    - tensorboard-plugin-wit==1.7.0
    - urllib3==1.25.9
    - werkzeug==1.0.1
    - xxhash==1.4.3
prefix: /home/paniv/miniconda3/envs/env_semantic_image_segmentation_py36
